Update postBuild

diff --git a/postBuild b/postBuild
--- a/postBuild
+++ b/postBuild
@@ -1,2 +1,10 @@
+
+
+#!/bin/bash
+set -eux  # fail fast and show commands
+
+echo "Testing if k3d is installed..."
+python -c "import k3d; print('k3d is available')"
+
 jupyter nbextension install --py --user k3d
 jupyter nbextension enable --py --user k3d
